package com.example.firebaseauthentication.utils

const val USERS = "users"
const val LOADING = "..."
const val LOGIN_SUCCESSFUL = "Login successful"
const val UNKNOWN_MODEL_CLASS = "unknown model class"
const val UNCHECKED_CAST = "UNCHECKED_CAST"
const val TAG = "TAG"
const val URL_IMAGE = "https://image.tmdb.org/t/p/original/"
const val POSTER = "poster"
const val NAME_OF_DB = "article_db"
const val RESULT_NAV = "result"
const val ERROR = "Error"
const val ENTER_EMAIL_PASSWORD = "Enter email and password"
const val EMAIL_NOT_EXIST = "Email does not exist"
const val FULL_NAME = "fullName"
const val EMAIL_NOT_VERIFIED = "Email is not verified, check your email"
const val NO_INTERNET = "No internet connection"
const val ENTER_REGISTERED_EMAIL = "Enter registered email"
const val RESET_EMAIL_SENT = "Reset email sent"
const val USER_REGISTERED = "User account registered, check your email"
const val EMAIL = "email"
const val FIELD_MUST_FILL = "Field must not be empty"
const val CONDITION_PASSWORD = "Password must not be less than 8"
const val EMAIL_EXIST = "Email already exist"
const val EMPTY_STRING = ""
const val RC_SIGN_IN = 123
const val COULD_NOT_SIGN_IN = "Couldn't sign in user"